sudo: required

language: python

python:
    - "2.7"

install:
    - export BIFROST_DIR=$(pwd)
    - cd
    - sudo apt-get update
    - sudo apt-get install exuberant-ctags -y
    - sudo pip install numpy matplotlib contextlib2 pint
    - git clone https://github.com/MatthieuDartiailh/pyclibrary
    - cd pyclibrary
    - python setup.py install
    - cd $BIFROST_DIR
    - NOCUDA=1 make
    - sudo make install 
    - export LD_LIBRARY_PATH=$(pwd)/lib/:/usr/local/lib
    - echo $LD_LIBRARY_PATH
    - cd ..
    
script:
    - cd bifrost/test 
    - sh ./download_test_data.sh
    - python -m unittest test_block test_sigproc test_resizing test_quantize test_unpack
