sudo: required

language: python

python:
    - "2.7"

services:
    - docker

install:
    - sudo apt-get install exuberant-ctags
    - sudo pip install numpy contextlib2 pint
    - make docker-cpu
    
script:
    - docker run --rm ledatelescope/bifrost /bin/sh -c "cd /bifrost/test && sh ./travis.sh"
