sudo: required

language: python

python:
    - "2.7"

services:
    - docker

install:
    - cd 
    - ls
    - pwd
    - sudo apt-get update
    - sudo apt-get install exuberant-ctags -y
    - sudo pip install numpy matplotlib contextlib2 pint
    - git clone https://github.com/MatthieuDartiailh/pyclibrary
    - cd pyclibrary
    - python setup.py install
    - cd ..
    - git clone https://github.com/ledatelescope/bifrost
    - cd bifrost
    - NOCUDA=1 make
    - sudo make install 
    - sudo find / -name "libbifrost.so"
    - export LD_LIBRARY_PATH=$(pwd)/lib/:/usr/local/lib
    - echo $LD_LIBRARY_PATH
    - cd ..
    
script:
    - cd bifrost/test 
    - sh ./travis.sh
